### PR TITLE
feat: add misty_moka flavor

### PR DESCRIPTION
**Pull request by luissolanodev**
Port from [aquarim-vim](https://github.com/FrenzyExists/aquarium-vim)
color scheme.

### CODE REVIEW

**Comment by LuisxSullivaN** [comment]
Hey! I kinda liked the colors used in aquarium-vim an thought of a port to catppuccino since it already has a lot of integrations.

**Comment by Pocco81** [comment]
Gosh... It's- it's breathtaking.... I LOVE IT! Feels like Nord, Neon Latte, GitHub dark and Sweet Mars, yet, it's none of those, it's something better...

The balance between the pink and the black is just, perfect. The eye candyness of this is mesmerizing.

**Comment by ViRu-ThE-ViRuS** [comment]
@LuisxSullivaN is this color scheme available in any fork?

**Comment by LuisxSullivaN** [comment]
@ViRu-ThE-ViRuS No, sorry. But you can take this repo, switch to the `old-catpuccin` (or something like that) branch and implement the changes in this PR, that way you can have it.

**Pull request closed without merging**
