### PR TITLE
feat: Add fidget.nvim integration

### LINKED ISSUE #269: feat: Add fidget.nvim integration

### PR DESCRIPTION
**Pull request by mslalith**
Closes #269

### CODE REVIEW

**Comment by nullchilly** [comment]
1. Don't create unnecessary issue and then link to it
2. Don't push the plugin higher up in the food-chain
3. Be sure to include the plugin in the integration list

**Comment by nullchilly** [comment]
Actually I think hiding the integration list to another file is better, nightfox for example have this https://github.com/EdenEast/nightfox.nvim#modules

Then our colorscheme won't be flooded with bloat impression

Thoughts? @maintainers

**Comment by gotgenes** [comment]
As a fidget user, I appreciate this improvement. Thanks, @mslalith!

>Don't push the plugin higher up in the config chain

@nullchilly I don't understand this statement. Is there something in this PR you're referring to?

>Actually I think hiding the integration list to another file is better, nightfox for example have this https://github.com/EdenEast/nightfox.nvim#modules

I think considering a code organization/API for plugin support like nightfox's is a great idea! I think it's beyond the scope of this PR. Maybe we can open a new issue to discuss that more?

**Review by gotgenes — APPROVED** [review]

**Comment by mslalith** [comment]
He meant to add the new plugins to the end of integrations table. @nullchilly you can correct me if I'm wrong

**Comment by nullchilly** [comment]
@mslalith Yes

Also you didn't update the [default configuration list](https://github.com/catppuccin/nvim/blob/c60c0c24599651fd99613078aa81f04123f0fb65/README.md#configuration) and [Integration list](https://github.com/catppuccin/nvim/blob/c60c0c24599651fd99613078aa81f04123f0fb65/README.md#-features)

**Comment by nullchilly** [comment]
@gotgenes I have created a new discussion https://github.com/catppuccin/nvim/issues/271

**Comment by nullchilly** [comment]
Please pay more attention to formatting in the future as currently we don't have a way to check format inside a markdown file

**Pull request merged**
