### PR TITLE
fix(float window): respect transparent background

### PR DESCRIPTION
**Pull request by emxxjnm**
Before:
WeChat832e1859784cd1ac8963195864993a2c

After:
WeChat8f64d612a1356ff4429fb25b5478abb3

### CODE REVIEW

**Comment by emxxjnm** [comment]
@nullchilly  soooo Sorry, this will cause the lsp float window background color to be confused, so should we roll back？😭
image

**Comment by nullchilly** [comment]
@emxxjnm How about mentioning the `:h winblend` option?

**Comment by nullchilly** [comment]
Hmm it works fine for me

image

**Comment by eXvimmer** [comment]
@nullchilly can you tell me how did you remove the background color from the floating window?
I have set the transparent-background to true, and it works perfectly, but floating windows have a background color. I want to make them like the picture above.

**Comment by eXvimmer** [comment]
@nullchilly Can you tell me how did you make lspsaga window (hover, peek and lsp_finder windows) transparent? I've set the winblend to 0, but it doesn't work.

**Comment by eXvimmer** [comment]
@nullchilly Can you tell me how did you make lspsaga window (hover, peek and lsp_finder windows) transparent? I've set the winblend to 0, but it doesn't work. I want it to look like the picture above.

**Comment by eXvimmer** [comment]
@nullchilly Can you tell me how did you make lspsaga window (hover, peek and lsp_finder windows) transparent? I've set the winblend to 0 and transparent_background to true, but it doesn't work. The weird is if I run CatppuccinCompile manually (each time) then hover and lsp_finder windows work, otherwise they don't.  I want saga to look like the picture above.

**Comment by eXvimmer** [comment]
@nullchilly or @emxxjnm Can you tell me how did you make **lspsaga** window (hover, peek and lsp_finder windows) transparent? I've set the `winblend` to 0 and `transparent_background` to true, but I have to run `:CatppuccinCompile` **manually** (each time) to make lspsaga transparent. I want saga to look like the picture above.

**Pull request merged**
