### PR TITLE
Fix feline integration

### PR DESCRIPTION
**Pull request by lispyclouds**
Fixes the feline integration in line with the recent refactoring.

### CODE REVIEW

**Comment by Pocco81** [comment]
Awesome! Thanks :) would it be possible for you to point the PR to the `dev` branch? If not then it's fine, we can make it work like that too 👍

**Comment by lispyclouds** [comment]
@Pocco81 done!

**Comment by lispyclouds** [comment]
looks like theres some more commits from the merge commits, trying another PR

**Comment by lispyclouds** [comment]
closing this in favour of https://github.com/catppuccin/nvim/pull/137

**Pull request closed without merging**
