### PR TITLE
Fix: TS-Rainbow

### PR DESCRIPTION
**Pull request by RAV64**
Removing unnecessary background highlighting since parenthesis should always have same background as the current background by default.

Before:

image

After:

image

### CODE REVIEW

**Comment by gotgenes** [comment]
@RAV64 Thanks for your contribution! It looks like your PR is failing on the StyLua check.

Do you have access to [StyLua](https://github.com/JohnnyMorganz/StyLua) on your system? If so, could you please run

```
stylua lua/catppuccin/groups/integrations/ts_rainbow.lua
```

and commit the changes?

The indentation in this project is with tabs not spaces, which is what I believe is why the StyLua check is failing.

**Comment by RAV64** [comment]
I was fairly certain that check was just bugged so I left it at that. Shouldn't there be stylua command ran on the project before every push? Hope It's good now :)

**Comment by RAV64** [comment]
Also there seems to be typo in the .editorconfig @gotgenes. Can I add commit that changes `indent_style = tabs` -> `indent_style = tab` since "tabs" isn't possible value for indent_style as stated here: https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties#indent_style. With this change my first commits should have passed.

**Comment by gotgenes** [comment]
Great catch on the editorconfig setting. Let's correct that as a separate PR.

Thanks for this contribution!

**Pull request merged**
