### PR TITLE
feat: Add markdown.nvim integration

### PR DESCRIPTION
**Pull request by ValdezFOmar**
Before

image

After

image

### CODE REVIEW

**Comment by ValdezFOmar** [comment]
I used the name `render_markdown` since there's already a `markdown` integration, but still tried to clarify in the README that the actual plugin is `markdown.nvim`.

**Comment by vollowx** [comment]
Maybe `markdown_nvim`?

**Comment by ValdezFOmar** [comment]
The plugin [suggests in its README](https://github.com/MeanderingProgrammer/markdown.nvim/tree/main/lua/render-markdown) the use of the name `render-markdown` to avoid collisions with other plugins, the actual [package](https://github.com/MeanderingProgrammer/markdown.nvim/tree/main/lua/render-markdown) uses the same name and the highlight groups and commands use `RenderMarkdown` as a prefix, so maybe is ok?

**Comment by vollowx** [comment]
Makes sense

**Review by vollowx — APPROVED** [review]

**Pull request merged**
