### PR TITLE
fix(compile): can't write inside /nix/store

### PR DESCRIPTION
**Pull request by nullchilly**

### CODE REVIEW

**Comment by MatthewCroughan** [comment]
I have verified this as working.

**Review by MatthewCroughan — APPROVED** [review]

**Review by EdenEast — APPROVED** [review]
Relates: #408

**Comment by nonetrix** [comment]
Still having this issue despite running NixOS unstable which seems to have this merged if I check the update date
image

**Comment by nullchilly** [comment]
@nonetrix This patch works if you call `require("catppuccin").setup()`

[A follow-up patch](https://github.com/catppuccin/nvim/commit/024b2aa5d5257e8f61b00057b3cc565fe939353a) to make it work without the need of setup function was sadly pushed 15 minutes late

**Comment by MatthewCroughan** [comment]
It already was updated to the HEAD of this repo 3 days ago https://github.com/NixOS/nixpkgs/pull/217416

@nonetrix just isn't using the version of Nixpkgs that contains the bump

**Comment by nullchilly** [comment]
https://github.com/figsoda/nixpkgs/blob/master/pkgs/applications/editors/vim/plugins/generated.nix#L14132

nix-unstable is at `22e55672793be043a5ce9790e7617322ef4ab445`

HEAD commit hash is `4175759297350557315987d479fb687a9f0b781f`

**Comment by MatthewCroughan** [comment]
@nullchilly yes, and that is the commit **after** you fixed the issue. When I said "latest HEAD", I mean the latest HEAD of 3 days ago, after you fixed the bug.

**Comment by MatthewCroughan** [comment]
And nixos-unstable contains this https://github.com/nixos/nixpkgs/blob/nixos-unstable/pkgs/applications/editors/vim/plugins/generated.nix#L14132 so the fix is in nixos-unstable too, which @nonetrix may not be using.

**Comment by MatthewCroughan** [comment]
@nonetrix if your system is a NixOS flake, then you can do the following to check what's going on:

In the following example, you can see that my Flake that defines all my systems is not using a version of Nixpkgs that contains the fix, whereas the current nixos-unstable does contain the fix.

```
user: matthew 🌐 swordfish in ~ took 53s 
❯ nix repl
Welcome to Nix 2.14.0pre20230224_92611e6. Type :? for help.

nix-repl> :lf github:matthewcroughan/nixcfg                                                     
Added 14 variables.

nix-repl> inputs.nixpkgs.outputs.legacyPackages.x86_64-linux.vimPlugins.catppuccin-nvim.src.rev
"6368edcd0b5e5cb5d9fb7cdee9d62cffe3e14f0e"

nix-repl> x = builtins.getFlake "github:nixos/nixpkgs/nixos-unstable"

nix-repl> x.outputs.legacyPackages.x86_64-linux.vimPlugins.catppuccin-nvim.src.rev
"22e55672793be043a5ce9790e7617322ef4ab445"
```

**Comment by nonetrix** [comment]
Not using a flake, but I plan to do that soon I guess another excuse to. Here are my configurations anyway https://github.com/nonetrix/nixdots

**Comment by MatthewCroughan** [comment]
It does not appear in that code that Nixpkgs is defined in Nix code, so it's not possible for me to see what version of Nixpkgs you're using just by looking at the code. This is because you're using Nix Channels, which are an impurity that only you are able to inspect by looking at your `$NIX_PATH` on your running system. Flakes fix that, and make it so that everything can be inspected just by looking at your code, and nothing comes from an environment variable on your running system.

You can run `nixos-version` on your running system and give me the output, that will tell us whether you're using a Nixpkgs that contains the fix.

**Comment by nonetrix** [comment]
23.05pre456790.988cc958c57 (Stoat)

**Comment by MatthewCroughan** [comment]
You're using the right nixpkgs version, it's just that you're not calling the setup function in the way @nullchilly suggested

**Comment by nullchilly** [comment]
@MatthewCroughan Like I mentioned before, my later commit fixed the need of `require("catppuccin").setup()`

**Comment by nonetrix** [comment]
I saw EOF << lua and I assumed I could just put it in my luaConfigExtras I'll try this in a minute

**Comment by MatthewCroughan** [comment]
@nullchilly Ah okay, Nixpkgs is currently not based on 024b2aa5d5257e8f61b00057b3cc565fe939353a it is based on 22e55672793be043a5ce9790e7617322ef4ab445 so doesn't contain that fix, it will be automatically updated eventually, or someone will get around to it.

**Pull request merged**
