### PR TITLE
Feat/add coc nvim support

### LINKED ISSUE #122: coc support request
Can we add [coc](https://github.com/neoclide/coc.nvim) support? The [docs](https://github.com/neoclide/coc.nvim/blob/master/doc/coc.txt) specify these colors can be updated:

```
*CocErrorHighlight* for error code range.
*CocWarningHighlight* for warning code range.
*CocInfoHighlight* for information code range.
*CocHintHighlight* for hint code range.
*CocDeprecatedHighlight* for deprecated code range, links to |CocStrikeThrough| by default.
*CocUnusedHighlight* for unnecessary code range, links to |CocFadeOut| by default.
```

I played around with it, but the current lua format for setting colors isn't working for me. I could use some help.

### PR DESCRIPTION
**Pull request by vinibispo**
Close #122

### CODE REVIEW

**Comment by vinibispo** [comment]
@Pocco81 Could you please review it?

**Comment by joshmedeski** [comment]
I'm setting it in my `init.lua` file:

```lua
require('catppuccin').setup {
  transparent_background = true,
  integrations = {
    coc_nvim = true,
  }
}
```

Then, I get the following error when booting up:

```
Error detected while processing /Users/joshmedeski/repos/dotfiles/mackup/.config/nvim/nvim-config/init.lu
a:
E5113: Error while calling lua chunk: .../repos/dotfiles/mackup/.config/nvim/nvim-config/init.lua:12: Vim
(lua):E5108: Error executing lua ...e/nvim/plugged/catppuccin/lua/catppuccin/core/mapper.lua:200: attempt
 to index a boolean value
stack traceback:
        ...e/nvim/plugged/catppuccin/lua/catppuccin/core/mapper.lua:200: in function 'get_integrations'
        ...e/nvim/plugged/catppuccin/lua/catppuccin/core/mapper.lua:224: in function 'apply'
        ...al/share/nvim/plugged/catppuccin/lua/catppuccin/main.lua:18: in function 'load'
        ...al/share/nvim/plugged/catppuccin/lua/catppuccin/main.lua:30: in function 'main'
        ...al/share/nvim/plugged/catppuccin/lua/catppuccin/init.lua:4: in function 'load'
        [string ":lua"]:1: in main chunk
        [C]: in function 'cmd'
        .../repos/dotfiles/mackup/.config/nvim/nvim-config/init.lua:12: in main chunk
stack traceback:
        [C]: in function 'cmd'
Press ENTER or type command to continue
```

I checked out the PR before making this update, is there something I'm missing?

**Comment by vinibispo** [comment]
I'm gonna fix it, sorry

**Comment by vinibispo** [comment]
@joshmedeski Can you try again?

**Comment by joshmedeski** [comment]
Screen Shot 2022-06-24 at 1 29 10 PM

It's working now, thanks!

**Comment by vinibispo** [comment]
Thank you for testing

**Comment by joshmedeski** [comment]
Thanks for the PR!

**Comment by Pocco81** [comment]
Thank you so much @vinibispo for the PR and @joshmedeski for testing it before it's merged :)

**Comment by gitzhangzhao** [comment]
Everything else works fine, but I want diagnostic to show undercurl，how to do it?

**Pull request merged**
