### PR TITLE
feat(barbecue): add barbecue

### PR DESCRIPTION
**Pull request by ofseed**
Coincidentally I found #376  after finishing it,
However, there are some differences between mine and his. 
The main difference is that I use Conceal for the file path and it uses Normal,
which is a part that is unique to barbecue and not available in navic.
image

### CODE REVIEW

**Comment by nullchilly** [comment]
Personally I think the folder path is a bit dim
@CnTeng thoughts?

**Comment by CnTeng** [comment]
I just copy the color from navic, maybe his choose is better.

**Comment by nullchilly** [comment]
This version's dirname is too dim, we should cherry picking from @CnTeng 's PR

**Comment by ofseed** [comment]
In fact, the dimed color is in recommended in barbecue's documentation. I think I can add an option to this pr for the user to decide this color later.

**Comment by ofseed** [comment]
@nullchilly Done. Now you can customize the dirname color yourself.

**Comment by ofseed** [comment]
And the new version of barbecue, which could generate colorscheme automatically, dims the dirname. So making it a default option is also a good choice.

**Pull request merged**
