### PR TITLE
Add FAQ Section for TrueColor

### PR DESCRIPTION
**Pull request by jdevries3133**
macOS's "Terminal.app" does not support TrueColor. It can be tricky to identify
what's going wrong when users encounter this issue. Hopefully this will point
them in the right direction by identifying that Terminal.app doesn't have the
color support that catppuccin requires.

### CODE REVIEW

**Comment by nullchilly** [comment]
Thanks you! I think this is the case for all terminal that does not support true color or isn't enabled by default

**Comment by jdevries3133** [comment]
Hm, I do understand that. I want to keep the keywords because I think they will get Ctrl + f hits. I know the presence of these certainly would have saved me some trouble. To that end, though, I'm ok with using that title but keeping the keywords in the body. 

What do you think? Do you think there might be additional keywords that might be worthwhile to include in the same vein?

**Comment by nullchilly** [comment]
Ah I didn't see your comment 1 minute ago

**Comment by nullchilly** [comment]
image

**Comment by jdevries3133** [comment]
LGTM, thanks!

**Pull request merged**
