### PR TITLE
Support overriding colors using vim.g.catppuccin_override_colors

### PR DESCRIPTION
**Pull request by 3rd**
This PR proposes a simple way to override the palette colors by setting the global variable `vim.g.catppucin_override_colors`.

Usage:
```lua
  vim.g.catppuccin_flavour = "mocha"
  vim.g.catppuccin_override_colors = {
    base = "#ff0000"
  }
  vim.cmd [[colorscheme catppuccin]]
```

### CODE REVIEW

**Comment by sandangel** [comment]
Nice. thanks @3rd for submitting the PR.

**Review by sandangel — APPROVED** [review]

**Comment by 3rd** [comment]
Hey, @sandangel
No problem, should it throw an error or print a message if a key in the user provided palette doesn't exist?
Should I add some documentation about it?

**Comment by sandangel** [comment]
sorry, I'm not the owner so not really can make decision. but from an engineer perspective:

> should it throw an error or print a message if a key in the user provided palette doesn't exist

I think so. Basically we should give feedback when user configure something wrong. A warning message would be better in term of user experience.

> Should I add some documentation about it?

Yes. To let user know about this feature and how to use it. So they won't open a new issue for this.

**Review by sandangel — APPROVED** [review]
LGTM

**Comment by sandangel** [comment]
hi @mainrs , could you please have a review on this PR?

**Comment by mainrs** [comment]
Hi! I am actually not familiar with `nvim`. I think one of the other contributors is better suited to review it.

**Comment by sandangel** [comment]
Oh sorry. @Pocco81 @vinibispo could you help?

**Review by vinibispo — APPROVED** [review]
It works perfectly

**Comment by andreasgrafen** [comment]
I've been staying out of this because I'm not maintaining this whatsoever. From a technical POV I think the changes are great, but I'd prefer to have Pocco have the last word in this, as this is his baby. :D

**Comment by Pocco81** [comment]
Sorry for the delay! I'm doing a rewrite of the plugin :)

**Comment by Pocco81** [comment]
from: https://github.com/catppuccin/nvim/pull/165/commits/62856bd8d54220f70118798df26965d03d2b20c1
>  feat: added color_overrides to settings

> the `g:catppuccin_override_colors` variable was removed in favour of a
setting in the user's Catppuccin conf. This commit also added the
ability to change individual colors per palette and also apply changes
to all of them.

**Comment by sandangel** [comment]
hi @Pocco81 , in that case can you fix the README? I think it's still referencing the old proposal from this PR.

**Pull request merged**
