### PR TITLE
Adding support to nvim-navic

### PR DESCRIPTION
**Pull request by augustocdias**
I added support to nvim-navic... I've tried to base the colors on the cmp and on treesitter. 

One issue that I'm not sure how to solve is the background. I thought putting `NONE` on all of them would make it transparent, but it is not happening, when I set it in lualine for example I'm getting the `base` background instead. Perhaps you could point me to how to solve this :)

### CODE REVIEW

**Comment by nullchilly** [comment]
What is that output of `:hi NavicIconsFile` ?

**Comment by augustocdias** [comment]
> What is the output of `:hi NavicIconsFile` ?

`NavicIconsFile xxx guifg=#1e66f5`

**Comment by nullchilly** [comment]
Hmm that's weird, maybe nvim-navic is overriding catppuccin. Can you investigate the loading order?

**Comment by nullchilly** [comment]
@augustocdias If you don't mind me commit directly to your repo

I will investigate for you :)

**Comment by nullchilly** [comment]
@augustocdias You have to enable highlight in nvim-navic

```lua
require("nvim-navic").setup {
	highlight = true,
}
```

**Comment by augustocdias** [comment]
@nullchilly  I did it. It is highlighting correctly, just the background that is not working.

**Comment by nullchilly** [comment]
@augustocdias Can you send screenshot? it was working for me...

**Comment by augustocdias** [comment]
Note that the background is the base instead of the mantle which is the one in this lualine section

image

**Comment by nullchilly** [comment]
You need to add custom highlight in that lualine section, it has no affiliation with nvim-navic

**Comment by augustocdias** [comment]
I set them in the integration... Wouldn't that be enough?

**Comment by nullchilly** [comment]
@augustocdias Try `:hi NavicIconsFile guibg="NONE"`

Then `:hi NavicIconsFile`

You can see that vim doesn't register guibg

**Comment by augustocdias** [comment]
So even if I set it through lualine, it is not respected. Should we add a config to allow setting a custom bg for navic instead of always setting it to NONE?

something like 
```
navic = {
    enabled = true,
    custom_bg = '#000000'
}
```

**Pull request merged**
