### PR TITLE
feat(neogit): update highlights (#545)

### PR DESCRIPTION
**Pull request by fdelacruz**

### CODE REVIEW

**Comment by fdelacruz** [comment]
What's the hold up??

**Comment by mrtnvgr** [comment]
> What's the hold up??

Could you send before/after screenshots please?

**Comment by fdelacruz** [comment]
@mrtnvgr 
Before
Screen Shot 2023-08-06 at 7 48 01 PM
After:
Screen Shot 2023-08-06 at 7 49 07 PM

**Comment by mrtnvgr** [comment]
> @mrtnvgr 
> Before:
> Screen Shot 2023-08-06 at 7 48 01 PM
> After:
> Screen Shot 2023-08-06 at 7 49 07 PM
> 

Thank you! Sorry for the delay.

**Comment by fdelacruz** [comment]
No, thank you for accepting my humble PR.

**Pull request merged**
