### PR TITLE
Added Felines new provider: macro and search count

### PR DESCRIPTION
**Pull request by ilias777**
Feline added new providers for macro recordings and search count.
This is useful if `cmdline=0`. By pressing `qa...` it's shows the recording next to the *position* component. Same for the search count. 
If you don't like the position of the two components, feel free to position them elsewhere.

macro

search_count

### CODE REVIEW

**Comment by nullchilly** [comment]
It should be enabled by default only if cmdheight=0

**Comment by arpangreat** [comment]
@ilias777 what font is that ?

**Comment by ilias777** [comment]
> It should be enabled by default only if cmdheight=0

Yes you are right!
Now is finish! The `macro` and the `search_count` are enabled only if `cmdheight=0`

**Comment by ilias777** [comment]
> @ilias777 what font is that ?

The font is [Cascadia Code](https://github.com/microsoft/cascadia-code)
This font is amazing!!!
If you are on Kitty Terminal, make sure you are enabled the font features of Cascadia Code in the `kitty.conf` file like so:
```
## CASCADIA CODE ##
font_family Cascadia Code
bold_font Cascadia Code Bold
italic_font Cascadia Code Italic
bold_italic_font Cascadia Code Bold Italic

## FONT FEATURES FOR CASCADIA CODE ##
font_features CascadiaCode-Italic calt +ss01 +ss02 +ss03 +ss04 +ss05 +ss07 +ss08 +zero +onum
```
This make the italic version even better 😉

**Comment by nullchilly** [comment]
cmdheight ftw ❤️

**Pull request merged**
