### PR TITLE
fix(feline): disable lsp status on nightly

### PR DESCRIPTION
**Pull request by mrtnvgr**
Hotfix for #509

### CODE REVIEW

**Review by nekowinston — APPROVED** [review]
Sorry for overlooking this as well, I was only testing on stable.

**Comment by nullchilly** [comment]
Please don't use version check

**Comment by nullchilly** [comment]
Also I just tested and `vim.lsp.status()[1]` doesn't work, did you test the PR at all before mering?

It should be `vim.lsp.status()` instead.

**Comment by mrtnvgr** [comment]
> Also I just tested and `vim.lsp.status()[1]` doesn't work, did you test the PR at all before merging?
> 
> It should be `vim.lsp.status()` instead.

I couldn't test myself, so I looked for similar fixes from other repositories. I saw suggestions and assumed that others had already checked it. I'm sorry.

**Comment by nullchilly** [comment]
Seems like it still doesn't work since the new `vim.lsp.status()` returns `87%: Loading workspace: 82/101, Loading workspace: 83/94` instead of a `{ message, percentage, tittle }`

**Comment by nullchilly** [comment]
The new output returns `73%: Loading workspace: 69/101, Loading workspace: 69/94` which breaks when feline do a string.format on it, i.e `string.format("%:")`

I think we should just disable this component on nightly instead of fighting to workaround.

**Pull request merged**
